- name: Create Roundcube directory for generated files
  ansible.builtin.file:
    path: "{{ roundcube_output_directory }}"
    state: directory
    mode: u+rwx

- name: Create Project
  ansible.builtin.include_role:
    name: common
    tasks_from: create-project
  vars:
    common_namespace_name: "{{ roundcube_project_name }}"
    common_output_directory: "{{ roundcube_output_directory }}"

- name: Prepare yaml file for {{ item }}
  ansible.builtin.template:
    src: "{{ item }}.yaml.j2"
    dest: "{{ roundcube_output_directory }}/{{ item }}.yaml"
    mode: u+rwx
  with_items:
    - serviceaccounts
    - secrets
    - configmaps
    - persistentvolumeclaims
    - rolebindings
    - services
    - deployments-db
    - deployments

- name: Add {{ item.name }}
  kubernetes.core.k8s:
    state: present
    src: "{{ roundcube_output_directory }}/{{ item.name }}.yaml"
    wait: true
    wait_sleep: "{{ item.wait_sleep }}"
    wait_timeout: "{{ item.wait_timeout }}"
  with_items:
    - {name: serviceaccounts, wait_sleep: 15, wait_timeout: 15}
    - {name: secrets, wait_sleep: 15, wait_timeout: 15}
    - {name: configmaps, wait_sleep: 15, wait_timeout: 15}
    - {name: persistentvolumeclaims, wait_sleep: 15, wait_timeout: 300}
    - {name: rolebindings, wait_sleep: 15, wait_timeout: 15}
    - {name: services, wait_sleep: 15, wait_timeout: 15}
    - {name: deployments-db, wait_sleep: 15, wait_timeout: 600}
    - {name: deployments, wait_sleep: 15, wait_timeout: 600}

- name: Get OCP Apps Endpoint
  ansible.builtin.include_role:
    name: common
    tasks_from: apps-endpoint
  vars:
    common_output_to_var: "apps_endpoint_domain"
  when: apps_endpoint_domain is not defined

- name: Crete Edge Route
  ansible.builtin.include_role:
    name: common
    tasks_from: create-edge-route
  vars:
    common_namespace_name: "{{ roundcube_project_name }}"
    common_route_name: "roundcube-{{ roundcube_project_name }}"
    common_service_name: roundcube-nginx
    common_apps_endpoint_domain: "{{ apps_endpoint_domain }}"
    common_output_directory: "{{ roundcube_output_directory }}"

- name: Set usage entry
  ansible.builtin.include_role:
    name: usage
    tasks_from: set-entry
  vars:
    usage_entry_name: Extras-Roundcube
    usage_entry_value:
      "# Roundcube

      As mail client.

      ## Endpoints

      - UI: https://roundcube-{{ roundcube_project_name }}.{{ apps_endpoint_domain }}

      ## Credentials

      - for admin: {{ lc_principal_admin_user }}@{{ lc_ldap_domain }} / {{ roundcube_universal_password }} \
        (you can also use only *{{ lc_principal_admin_user }}* without domain as username to login)
      
      - for other users: cpadmin1, cpadmin2, cpuser, cpuser1, cpuser2 with domain @{{ lc_ldap_domain }} / {{ roundcube_universal_password }} \
        (you can also use only the usernames without domain to login)

      "
