

#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#         ________  __  ___     ___    ________       
#        /  _/ __ )/  |/  /    /   |  /  _/ __ \____  _____
#        / // __  / /|_/ /    / /| |  / // / / / __ \/ ___/
#      _/ // /_/ / /  / /    / ___ |_/ // /_/ / /_/ (__  ) 
#     /___/_____/_/  /_/    /_/  |_/___/\____/ .___/____/  
#                                           /_/
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing CP4WAIOPS
#
#  CloudPak for Watson AIOps
#
#  ¬©2022 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Installs:
#
#  - Turbonomic
#  - Turbonomic Demo Content
#     - Demo User
#     - RobotShop Demo App with synthetic metric
#     - Instana target (if Instana is installed - you have to enter the API Token Manually)
#     - Groups for vCenter and RobotShop
#     - Groups for licensing
#     - Resource Hogs
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
 
 
 
- name: ‚ú¥Ô∏è ‚ú¥Ô∏è ‚ú¥Ô∏è INSTALLATION MODULE START - {{current_cp4waiops_feature.kind}}
  debug: 
    msg: 
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "                                                                                                                                                   "
    - "      üöÄ CloudPak for Watson AIOps - INSTALLING {{current_cp4waiops_feature.kind}}                                                                                          "
    - "                                                                                                                                                   "
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"


# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Check Login
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
- name:   üöÄ INITIALIZATION - Get Cluster FQDN
  shell: |
    CLUSTER_ROUTE=$(oc get routes console -n openshift-console | tail -n 1 2>&1 ) 
    CLUSTER_FQDN=$( echo $CLUSTER_ROUTE | awk '{print $2}')
    echo ${CLUSTER_FQDN##*console.}
  register: CLUSTER_NAME


- name:   üöÄ INITIALIZATION - Check Cluster Connectivity
  fail: msg="You must be logged in to the server!"
  when: CLUSTER_NAME.stdout==""




- name: üü£ Installing {{current_cp4waiops_feature.kind}} with the following configuration
  debug:
    var: current_cp4waiops_feature





# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Check Encrypted Licenses
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
- name: Get Licenses 
  block:

  - name: üíæ SET Turbo License from Config File - {{current_cp4waiops_feature.turbo_license | default("NONE")}} 
    set_fact: current_turbo_license={{current_cp4waiops_feature.turbo_license| default("NONE")}}



- name: Decrypt Licenses 
  block:
  - name: Create Token File
    shell: |
      echo {{global_config.license_token}} > /tmp/pwd.yaml
    ignore_errors: true


  - name: Get License from Vault
    shell: |
      OS=$(uname -s | tr '[:upper:]' '[:lower:]')
      if [ "${OS}" == "darwin" ]; then
            echo "MAC"
            LICENSE_FILE=$(pwd)"/roles/cp4waiops-turbonomic-demo-content/vars/lic.yaml"
      else
            LICENSE_FILE="{{role_path}}/vars/lic.yaml"
      fi    
      echo $LICENSE_FILE
      ansible-vault decrypt --vault-password-file /tmp/pwd.yaml --output /tmp/license.yaml "$LICENSE_FILE"
    ignore_errors: true


  - name: Include License from Vault
    ansible.builtin.include_vars:
      file: /tmp/license.yaml
      name: licenses
    ignore_errors: true


  - name: Cleanup
    shell: |
      rm /tmp/pwd.yaml
      rm /tmp/license.yaml
    ignore_errors: true

      
  - name: üíæ SET Turbo License from Vault
    set_fact: current_turbo_license={{licenses.turbo_license }} 



  when: global_config.license_token is defined 




- name:  üü£ Check Turbo License"
  debug:
    msg:
    - "** Missing License Information ***********************************************************************"
    - " Turbo License:      {{ current_turbo_license}}"
    - " ‚ùå Most of the customization won't work...."
    - ""
  when: current_turbo_license == "NONE"




- name:  üü¢ Turbo License - OK"
  debug:
    msg:
    - "** License Information ***********************************************************************"
    - " Turbo License:      {{ current_turbo_license}}"
    - " ‚úÖ OK...."
    - ""
    verbosity: 2
  when: current_turbo_license != "NONE"








# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INITIALIZATION
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Placeholder for customization
- name: üì• Init Custom Hook
  include_tasks: 00_init-custom-hook.yaml

# Initialize Logging
- name: üì• Init Logging
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/01_init-logging.yaml"

  
# Start block
- name: üì• Start Logging
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/90-log-start.yaml"




# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INSTALL TURBONOMIC DEMO CONTENT
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Install TURBONOMIC
- name: üì• Install Turbonomic
  include_tasks: 10_addons-turbonomic-demo-content.yaml


# Update AI Manager Cards
- name: üì• Update AI Manager Cards
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/99_update_cards.yaml"





- name: üì• End Logging
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/91-log-end.yaml"





- name: ‚úÖ INSTALLATION MODULE DONE - {{current_cp4waiops_feature.kind}}
  debug: 
    msg:  

    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "                                                                                                                                                   "
    - "       ‚úÖ CloudPak for Watson AIOps - DONE INSTALLING {{current_cp4waiops_feature.kind}}                                                                                 "
    - "                                                                                                                                                   "
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
