

#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#       __________  __ ___       _____    ________            
#      / ____/ __ \/ // / |     / /   |  /  _/ __ \____  _____
#     / /   / /_/ / // /| | /| / / /| |  / // / / / __ \/ ___/
#    / /___/ ____/__  __/ |/ |/ / ___ |_/ // /_/ / /_/ (__  ) 
#    \____/_/      /_/  |__/|__/_/  |_/___/\____/ .___/____/  
#                                              /_/            
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing CP4WAIOPS
#
#  CloudPak for Watson AIOps
#
#  ¬©2022 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Installs:
#
#  - Turbonomic
#  - Turbonomic Demo Content
#     - Demo User
#     - RobotShop Demo App with synthetic metric
#     - Instana target (if Instana is installed - you have to enter the API Token Manually)
#     - Groups for vCenter and RobotShop
#     - Groups for licensing
#     - Resource Hogs
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
 
 
 
- name: ‚ú¥Ô∏è ‚ú¥Ô∏è ‚ú¥Ô∏è INSTALLATION MODULE START - {{current_cp4waiops_feature.kind}}
  debug: 
    msg: 
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "                                                                                                                                                   "
    - "      üöÄ CloudPak for Watson AIOps - INSTALLING {{current_cp4waiops_feature.kind}}                                                                                          "
    - "                                                                                                                                                   "
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"



- name: üü£ Installing {{current_cp4waiops_feature.kind}} with the following configuration
  debug:
    var: current_cp4waiops_feature



- name:  üü£ ‚ùó‚ùó‚ùó‚ùó This script will wait until you have initialised Turbonomic with password P4ssw0rd!"
  debug:
    msg:
    - " - Open Turbonomic"
    - " - Set initial Password to P4ssw0rd!"





# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INITIALIZATION
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Placeholder for customization
- name: üì• Init Custom Hook
  include_tasks: 00_init-custom-hook.yaml

# Initialize Logging
- name: üì• Init Logging
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/01_init-logging.yaml"

  
# Start block
- name: üì• Start Logging
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/90-log-start.yaml"




# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INSTALL TURBONOMIC DEMO CONTENT
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Install TURBONOMIC
- name: üì• Install Turbonomic
  include_tasks: 10_addons-turbonomic-demo-content.yaml


# Update AI Manager Cards
- name: üì• Update AI Manager Cards
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/99_update_cards.yaml"





- name: üì• End Logging
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/91-log-end.yaml"





- name: ‚úÖ INSTALLATION MODULE DONE - {{current_cp4waiops_feature.kind}}
  debug: 
    msg:  

    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "                                                                                                                                                   "
    - "       ‚úÖ CloudPak for Watson AIOps - DONE INSTALLING {{current_cp4waiops_feature.kind}}                                                                                 "
    - "                                                                                                                                                   "
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
