---
- name: Get first compute node
  shell: |
    oc get no --no-headers -l node-role.kubernetes.io/worker -o custom-columns='name:.metadata.name' | head -1
  register: _ocp_compute_nodes

- name: Retrieve /etc/crio/crio.conf
  shell: |
    oc debug no/{{ _ocp_compute_nodes.stdout }} -- cat /host/etc/crio/crio.conf > {{ cloud_pak_prepare_ocp_temp_dir.path }}/cp4d-crio.conf
  register: debug_node_result
  retries: 3
  delay: 10
  until: debug_node_result.rc==0

- name: Set pids_limit
  community.general.ini_file:
    path: "{{ cloud_pak_prepare_ocp_temp_dir.path }}/cp4d-crio.conf"
    section: "crio.runtime"
    option: pids_limit
    value: "12288"

# - name: Set default_ulimits
#   community.general.ini_file:
#     path: "{{ cloud_pak_prepare_ocp_temp_dir.path }}/cp4d-crio.conf"
#     section: "crio.runtime"
#     option: default_ulimits
#     value: '[ "nofile=66560:66560" ]'

- name: Create CRI-O Machine Config
  include_tasks: create-crio-config.yml
  when: _mco_exists

- name: Apply CRI-O configuration if the Machine Config Operator does not exist
  include_tasks: non-mco-apply-crio-config.yml
  when: not _mco_exists