---
# Create all catalog sources

- name: ðŸ“¥ Create catalog sources for IBM operator catalog when not using case files
  template:
    src: create-ibm-operator-catalog-source.j2
    dest: "{{ status_dir }}/cp4waiops/cp4wa-catalog-sources.yml"

- name: ðŸ“¥ Install CatalogSources from {{ status_dir }}/cp4waiops/cp4wa-catalog-sources.yml
  shell: |
    oc apply -f {{ status_dir }}/cp4waiops/cp4wa-catalog-sources.yml
