---
- set_fact:
    _case_dir: "{{ status_dir  | default('temp_status') }}/cp4waiops/case"

# Install catalog
- name: ðŸ“¥ Compose cloudctl install-catalog command for case file
  set_fact:
    _install_catalog_command: "{{ lookup('template','install-catalog-command.j2') }}"

- name: ðŸ“¥ Show install-catalog command that will be used
  debug:
    var: _install_catalog_command

- name: ðŸš€ Run cloudctl install-catalog for case file
  shell: |
    {{ _install_catalog_command }}
  