---
- name: Get generator to be used for platform {{ cloud_platform }}
  include_tasks: get-generator-dir.yaml

- name: Run generators
  include_tasks: "{{_generator_dir}}/{{ GENERATOR_NAME }}/main.yaml"
  vars:
    generator:
      name: "{{ GENERATOR_NAME }}"
      path: "{{ _generator_dir }}/{{ GENERATOR_NAME }}"
      attributes: "{{ GENERATOR_ATTRIBUTES }}"
      config: "{{ all_config }}"
    PATH_TO_TERRAFORM_WORK_DIR: "{{status_dir}}/terraform"
  when: cloud_platform == 'ibm-cloud'