---
<<<<<<< HEAD
- name: "Install Watson Studio runtimes for cartridge {{ _current_cp4d_cartridge.olm_utils_name }}"
  debug:
    msg: ""

- name: Install runtime {{ _ws_runtime }}
  include_tasks: cp4d-install-cr-ws_runtime.yml
  loop: "{{ _current_cp4d_cartridge.runtimes | default([]) }}"
  loop_control:
    loop_var: _ws_runtime
=======
- include_tasks: cp4d-install-cr-ws_runtimes-apply-cr.yml
  when: _p_cp4d_version < '5.3.0'

- include_tasks: cp4d-install-cartridges-install-components.yml
  vars:
    _p_apply_cartridges: "[{{ _current_cp4d_cartridge }}]"
  when: _p_cp4d_version >= '5.3.0'
>>>>>>> main
