---
# Create CR if cartridge state is installed
- block:
  - name: Create custom resources for CP4D cartridge
    debug:
      msg: "Creating custom resources for CP4D cartridge {{ _current_cp4d_cartridge.name }} for CP4D cluster {{ _p_current_cp4d_cluster.project }}"

  - name: Show cartridge details
    debug:
      var: _current_cp4d_cartridge

  # Run the pre-processing script if one has been specified
  - name: "Run the custom resource pre-processing script {{ _current_cp4d_cartridge.cr_preprocessing_script }}"
    include_tasks: "{{ _current_cp4d_cartridge.cr_preprocessing_script }}"
    when: (_current_cp4d_cartridge.cr_preprocessing_script | default('')) != ''
    
  - name: "Validate if the Custom Resource file for {{ _current_cp4d_cartridge.name }} exists"
    stat:
      path: "{{ role_path }}/templates/{{ _current_cp4d_cartridge.cr_file_prefix }}-cr.j2"
    register: _cr_file_exists_result

  - name: Determine if the template for the CR exists
    debug:
      msg: "Customer Resource File {{ role_path }}/templates/{{ _current_cp4d_cartridge.cr_file_prefix }}-cr.j2 does not exist. Skip creating CR for cartridge {{ _current_cp4d_cartridge.name }}"
    when: not _cr_file_exists_result.stat.exists

  - block:
      - name: Fail if the CR for cartridge has not been found
        fail:
          msg: "CR for cartridge {{ _current_cp4d_cartridge.name }} not found, cannot check if CR is successfully installed"
        when: 
        - (_current_cp4d_cartridge.cr_cr | default("")) == ""

      # Create CR
      - name: Prepare yaml file for custom resource {{ _current_cp4d_cartridge.cr_cr }} for cartridge {{ _current_cp4d_cartridge.name }}
        template:
          src: "{{ _current_cp4d_cartridge.cr_file_prefix }}-cr.j2"
          dest: "{{ status_dir }}/cp4d/{{ _p_current_cp4d_cluster.project }}-{{ _current_cp4d_cartridge.name }}-cr.yml"

      - name: Create CR for cartridge {{ _current_cp4d_cartridge.name }}
        command: |
          oc apply -f "{{ status_dir }}/cp4d/{{ _p_current_cp4d_cluster.project }}-{{ _current_cp4d_cartridge.name }}-cr.yml"
        register: _cr_create_result
        retries: 10
        delay: 30
        until: _cr_create_result.rc == 0
        vars:
          ansible_callback_diy_runner_retry_msg: >-
            {%- set result = ansible_callback_diy.result.output -%}
            {%- set retries_left = result.retries - result.attempts -%}
            Retrying: {{ ansible_callback_diy.task.name }} ({{ retries_left }} Retries left) ...        
        
    when: 
    - _cr_file_exists_result.stat.exists
    
  when: 
  - (_current_cp4d_cartridge.state | default('installed')) == 'installed'
  - not _current_cp4d_cartridge.name in ['cpfs','cp-foundation','cpd_platform','lite','scheduler']
  - not (_current_cp4d_cartridge.cr_internal | default(False) | bool)
