---
- include_tasks: cp4d-install-cr-ws_runtimes-apply-cr.yml
  when: _p_cp4d_version < '5.3.0'

- include_tasks: cp4d-install-cartridges-install-components.yml
  vars:
    _p_apply_cartridges: "[{{ _current_cp4d_cartridge }}]"
  when: _p_cp4d_version >= '5.3.0'