---
- name: Insert wkc options into {{ status_dir }}/cp4d/{{ _p_current_cp4d_cluster.project }}-install-options.yml
  blockinfile:
    path: "{{ status_dir }}/cp4d/{{ _p_current_cp4d_cluster.project }}-install-options.yml"
    marker: "# {mark} watsonx_ai options #"
    block: |2
        watsonx_ai:
          tuning_disabled: {{ _current_cp4d_cartridge.installation_options.tuning_disabled | default(false) }}