---
- name: Check if cartridge installation options file exists
  stat:
    path: "{{ status_dir }}/cp4d/{{ _p_current_cp4d_cluster.project }}-{{ _current_cp4d_cartridge.olm_utils_name }}-install-options.yml"
  register: _cartridge_install_options_file

- include_role:
    name: log-deployer-activity
  vars:
    _p_activity_description: "Installation options file for install-component of cartridge {{ _current_cp4d_cartridge.olm_utils_name }}"
    _p_activity_yaml: "{{ status_dir }}/cp4d/{{ _p_current_cp4d_cluster.project }}-{{ _current_cp4d_cartridge.olm_utils_name }}-install-options.yml"
  when: _cartridge_install_options_file.stat.exists

- name: Generate install-components command to install cartridge {{ _current_cp4d_cartridge.olm_utils_name }}
  set_fact:
    _install_components_command: "{{ lookup('template', 'install-components-separate.j2') }}"
  vars:
    _p_preview_script: False

- include_role:
    name: run-command
  vars:
    _p_command_description: Run install-components command to install cartridge {{ _current_cp4d_cartridge.olm_utils_name }}
    _p_command: "{{ _install_components_command }}"
    _p_command_log_file: "{{ status_dir }}/log/{{ _p_current_cp4d_cluster.project }}-{{ _current_cp4d_cartridge.olm_utils_name }}-install-components.log"
    _p_command_failed_when: False
  environment:
    OLM_UTILS_IMAGE: "{{ _olm_utils_image_full }}"

- block:
  - set_fact:
      _install_cartridges_result: "{{ _run_command_result }}"

  - name: Fail if there was an error installing the cartridge {{ _current_cp4d_cartridge.olm_utils_name }} using install-components
    fail:
      msg: "{{ _install_cartridges_result }}"
    when: 
    - _install_cartridges_result.rc!=0
    - not (cpd_test_cartridges | default(False) | bool)
    
  - set_fact:
      _cp4d_cartridges_installed_successfully: False
    when: _install_cartridges_result.rc!=0
  when: not cpd_dry_run