---
- name: "Install cartridge {{ _current_cp4d_cartridge.olm_utils_name }}"
  debug:
    msg: ""

- name: Ensure that OLM utils work directory exists
  file:
    path: /tmp/work
    state: directory

- name: Write license type to /tmp/work/replication-install-options.yml
  copy:
    content: "license_type: {{ _current_cp4d_cartridge.license }}"
    dest: "/tmp/work/replication-install-options.yml"

# Always generate the preview script to log what will be done
- name: "Generate command preview script to install cartridge {{ _current_cp4d_cartridge.olm_utils_name }}"
  set_fact:
    _apply_cr_command_script: "{{ lookup('template', 'apply-cr-replication.j2') }}"
  vars:
    _p_preview_script: True 

- name: Show apply-cr command to install cartridges
  debug:
    var: _apply_cr_command_script

- name: Generate preview script to install cartridge {{ _current_cp4d_cartridge.olm_utils_name }}, logs are in {{ status_dir }}/log/{{ _p_current_cp4d_cluster.project }}-apply-cr-cartridges.log
  shell: |
    {{ _apply_cr_command_script }} > {{ status_dir }}/log/{{ _p_current_cp4d_cluster.project }}-apply-cr-cartridges.log 2>&1

- name: Copy script to {{ status_dir }}/cp4d/{{ _p_current_cp4d_cluster.project }}-apply-cr-replication.sh
  copy:
    src: "/tmp/work/preview.sh"
    dest: "{{ status_dir }}/cp4d/{{ _p_current_cp4d_cluster.project }}-apply-cr-replication.sh"
    remote_src: True
    mode: u+rwx

- name: Run apply-cr command to install cartridge {{ _current_cp4d_cartridge.olm_utils_name }}
  block:
  - name: Generate apply-cr command to install cartridge {{ _current_cp4d_cartridge.olm_utils_name }}
    set_fact:
      _apply_cr_command: "{{ lookup('template', 'apply-cr-replication.j2') }}"
    vars:
      _p_preview_script: False
  - name: Run apply-cr command to install cartridge {{ _current_cp4d_cartridge.olm_utils_name }}, logs are in {{ status_dir }}/log/{{ _p_current_cp4d_cluster.project }}-apply-cr-cartridges.log
    shell: |
      {{ _apply_cr_command }} > {{ status_dir }}/log/{{ _p_current_cp4d_cluster.project }}-apply-cr-cartridges.log 2>&1
    register: _install_cartridges_result
    failed_when: False
  - name: Fail if there was an error installing the cartridge {{ _current_cp4d_cartridge.olm_utils_name }} using apply-cr
    fail:
      msg: "{{ _install_cartridges_result }}"
    when: 
    - not _install_cartridges_result.rc!=0
    - not (cpd_test_cartridges | default(False) | bool)
  - set_fact:
      _cp4d_cartridges_installed_successfully: False
    when: _install_cartridges_result.rc!=0
  when: _sequential_install

- name: Run shell script to install cartridge {{ _current_cp4d_cartridge.olm_utils_name }}, logs are in {{ status_dir }}/log/{{ _p_current_cp4d_cluster.project }}-apply-cr-cartridges.log
  shell: |
    {{ status_dir }}/cp4d/{{ _p_current_cp4d_cluster.project }}-apply-cr-replication.sh >> {{ status_dir }}/log/{{ _p_current_cp4d_cluster.project }}-apply-cr-cartridges.log 2>&1
  when: not _sequential_install