---
<<<<<<< HEAD
- name: Set installation options for watsonx.data integration
  include_tasks: cp4d-installation-options.yml
  vars:
    _cartridge_name: watsonx_dataintegration
    _root_options: False

=======
>>>>>>> main
- include_tasks: cp4d-prep-wxd-integration-postgres.yml
  when: _p_cp4d_version=='5.3.0'