---
- block:
  - name: Write cartridge information to file {{ status_dir }}/log/{{ _p_current_cp4d_cluster.project }}-cartridges.json
    copy:
      content: "{{ _cartridges_to_install | default([]) | to_json }}"
      dest: "{{ status_dir }}/log/{{ _p_current_cp4d_cluster.project }}-cartridges.json"

  - name: Wait until cartridge {{ _current_cp4d_cartridge.name }} has been installed, check logs in {{ status_dir }}/log/{{ _p_current_cp4d_cluster.project }}-cartridges.log
    script: |
      check-services-installed.sh \
        {{ status_dir }} \
        {{ _p_current_cp4d_cluster.project }} \
        {{ _current_cp4d_cartridge.name }}
        
    register: _wait_cartridges_result
    until: _wait_cartridges_result.rc!=0 or _wait_cartridges_result.stdout.find('cartridge installation successfully completed') != -1
    retries: "{{ _v_cartrige_install_wait_retries }}"
    failed_when: False
    delay: 120
    vars:
      ansible_callback_diy_runner_retry_msg: >-
        {%- set result = ansible_callback_diy.result.output -%}
        {%- set retries_left = result.retries - result.attempts -%}
        Retrying: {{ ansible_callback_diy.task.name }} ({{ retries_left }} Retries left) ...

  - set_fact:
      _cp4d_cartridges_installed_successfully: False
    when: _wait_cartridges_result.rc!=0 or _wait_cartridges_result.stdout.find('cartridge installation successfully completed') == -1

  - name: Fail if there was an error waiting for the cartridge(s) to be installed
    fail:
      msg: "{{ _wait_cartridges_result }}"
    when: 
    - not _cp4d_cartridges_installed_successfully
    - not (cpd_test_cartridges | default(False) | bool)

  when: 
  - not _current_cp4d_cartridge.name in ['cpfs','cp-foundation','cpd_platform','lite','scheduler']
  - not (_current_cp4d_cartridge.cr_internal | default(False) | bool)