# Based on https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/latest?topic=operator-preparing-log-file-storage

- name: Clone cert-kubernetes repo
  ansible.builtin.git:
    repo: https://github.com/Vincent-Le/cert-kubernetes-beta.git
    # repo: https://github.com/icp4a/cert-kubernetes.git
    dest: "{{ cp4ba_output_directory }}/cert-kubernetes"
    # single_branch: true from 2.11 only
    version: "{{ cp4ba_cert_k8s_branch }}"
  retries: 5
