

#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#       __________  __ ___       _____    ________            
#      / ____/ __ \/ // / |     / /   |  /  _/ __ \____  _____
#     / /   / /_/ / // /| | /| / / /| |  / // / / / __ \/ ___/
#    / /___/ ____/__  __/ |/ |/ / ___ |_/ // /_/ / /_/ (__  ) 
#    \____/_/      /_/  |__/|__/_/  |_/___/\____/ .___/____/  
#                                              /_/            
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing CP4WAIOPS
#
#  CloudPak for Watson AIOps
#
#  Â©2022 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Installs:
#
#  - WAIOPS Operator
#  - AI Manager
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
 


- name: ðŸš€ INSTALLATION MODULE START - {{current_cp4waiops_feature.kind}}
  debug: 
    msg: 
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "                                                                                                                                                   "
    - "       ðŸš€ CloudPak for Watson AIOps - INSTALLING {{current_cp4waiops_feature.kind}} "
    - "                                                                                                                                                   "
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»ðŸ”»"



- name: ðŸŸ¢ Installing {{current_cp4waiops_feature.kind}} with the following configuration
  debug:
    var: current_cp4waiops_feature


- name:  ðŸŸ¢ Storage Class Parameters - SPECIFIC INSTANCE"
  debug:
    msg:
    - "** Installation Options for SPECIFIC INSTANCE ***********************************************************************"
    - " Storage Class File Override:      {{ current_cp4waiops_feature.storage_class_file}}"
    - " Storage Class Block Override:     {{ current_cp4waiops_feature.storage_class_block}}"
    - " Storage Class InfraManagement:    {{ current_cp4waiops_feature.storage_class_file}}"
    - ""
  when: current_cp4waiops_feature.storage_class_file is defined


- name:  ðŸŸ¢ Storage Class Parameters - GLOBAL"
  debug:
    msg:
    - "** Installation Options from GLOBAL ***********************************************************************"
    - " Storage Class File Override:      {{ all_config.openshift[0].openshift_storage[0].ocp_storage_class_file}}"
    - " Storage Class Block Override:     {{ all_config.openshift[0].openshift_storage[0].ocp_storage_class_block}}"
    - " Storage Class InfraManagement:    {{ all_config.openshift[0].openshift_storage[0].ocp_storage_class_file}}"
    - ""
  when: current_cp4waiops_feature.storage_class_file is not defined and all_config.openshift[0].openshift_storage[0].ocp_storage_class_file is defined


# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INITIALIZATION
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Placeholder for customization
- name: ðŸ“¥ Init Custom Hook
  include_tasks: 00_init-custom-hook.yaml

# Initialize Logging
- name: ðŸ“¥ Init Logging
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/01_init-logging.yaml"
    
- name: ðŸ“¥ Checks
  include_tasks: 02_init_checks.yaml
# Start block
- name: ðŸ“¥ Start Logging
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/90-log-start.yaml"

# Run Prerequisites
- name: ðŸ“¥ Initialization
  include_tasks: 03_init-initialization.yaml
  

- name: ðŸ“¥ Get Storage Class
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/05_init-get-storage-class.yaml"


- name: ðŸ“¥ AI Manager Prerequisites 
  include_tasks: 06_aimanager-prerequisites.yaml
      

# Install CP4WAIOPS Operator
- name: ðŸ“¥ AI Manager Custom Hook
  include_tasks: 08_aimanager-custom-hook.yaml

# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INSTALL CATALOG with YAML FILE
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
- name: ðŸ“¥ Install AI Manager Catalog - Classic Way
  include_tasks: 10_aimanager-catalog.yaml
  when: current_cp4waiops_feature.case_install==false


# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INSTALL CATALOG with CASE FILE
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# - name: ðŸ“¥ Install AI Manager Catalog - Save Case File (this can take some time)
#   include_role:
#     name: cp4waiops-case-save
#   when: current_cp4waiops_feature.case_install==true


# - name: ðŸ“¥ Install AI Manager Catalog - Create CatalogSources from Case File (this can take some time)
#   include_role:
#     name: cp4waiops-case-catalog-source
#   when: current_cp4waiops_feature.case_install==true



# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INSTALL AI MANAGER
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
- name: ðŸ“¥ Install AI Manager Operator
  include_tasks: 11_aimanager-operator.yaml


# Install CP4WAIOPS Instance
- name: ðŸ“¥ Install AI Manager Instance
  include_tasks: 12_aimanager-install.yaml
      




# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# WAIT FOR INSTALLATION READY
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Wait for Common Services being completely installed
- name: ðŸ“¥ Wait for CommonServices
  include_tasks: 99_aimanager-wait-common-services.yaml
- name: ðŸ“¥ Wait for Zen Initialisation
  include_tasks: 99_aimanager-wait-for-zen.yaml
      

# Patching Topology Deployment
- name: ðŸ“¥ Patch Topology
  include_tasks: 20_aimanager-patch-topology.yaml


# Wait for CP4WAIOPS being completely installed
- name: ðŸ“¥ Wait for AI Manager
  include_tasks: 99_aimanager-wait-cp4waiops.yaml

# --------------------------------------------------------------------------------------------------------------------------------------
# Create Openshift WebConsole Menu Item
# --------------------------------------------------------------------------------------------------------------------------------------
- name: ðŸ“¥  Create AI Manager Openshift WebConsole Menu Item
  include_tasks: 91_aimanager-create-ocp-menu.yaml


  
# Access and documentaiton
- name: ðŸ“¥ Get all logins
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/90_core-get-all-logins.yaml"



- name: ðŸ“¥ Open AI Manager
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/99_open-aimanager.yaml"


- name: ðŸ“¥ Open Documentation
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/99_open-doc.yaml"



- name: ðŸ“¥ End Logging
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/91-log-end.yaml"






- name: âœ… INSTALLATION MODULE DONE - {{current_cp4waiops_feature.kind}}
  debug: 
    msg: 
    - "ðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”ºðŸ”º"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "                                                                                                                                                   "
    - "       âœ… CloudPak for Watson AIOps - DONE INSTALLING {{current_cp4waiops_feature.kind}}                                                                                 "
    - "                                                                                                                                                   "
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
