---
- name: Get all current Cognos Analytics instances
  uri:
    url: 'https://{{ cp4d_url.stdout }}/zen-data/v3/service_instances?addon_type={{ cp4d_cognos_instance_addon_type }}'
    method: GET
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ _cp4d_bearer_token }}"
    return_content: yes
    validate_certs: no
    status_code: 200
  register: _all_cognos_instances
  when: not cpd_dry_run

# Loop through all deployed Cognos Analytics instance definitions to check if instance no longer exists in the config
- name: Loop through each Cognos Analytics instance to check if it must be deleted
  include_tasks: delete_cognos_instance.yml
  loop: "{{ _all_cognos_instances.json.service_instances | default([]) }}"
  loop_control:
    loop_var: _cognos_instance