

# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Patching some stuff
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
    

- name: üõ∞Ô∏è  START - OCP MENU
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"


- name: Log
  shell: |
    export MESSAGE="Create Openshift WebConsole Menu Item"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_cp4waiops_feature.kind}}.log
    echo $currentDate" - "$MESSAGE  >> ../install_{{current_cp4waiops_feature.kind}}.log
  ignore_errors: true
   


- name: üåè OCP MENU - Create Openshift WebConsole Menu Item
  shell: |
    export EVTMGR_NAMESPACE=$(oc get po -A|grep noi-operator |awk '{print$1}')
    appURL=$(oc get route -n $EVTMGR_NAMESPACE  evtmanager-ibm-hdm-common-ui -o jsonpath={.spec.host})|| true

    cat <<EOF | oc apply -f -
      apiVersion: console.openshift.io/v1
      kind: ConsoleLink
      metadata:
        name: cp4waiops-eventmanager
      spec:
        applicationMenu:
          imageURL: >-
            https://raw.githubusercontent.com/niklaushirt/cp4waiops-deployer/main/doc/pics/icons/microservices--1.svg
          section: IBM Cloud Paks
        href: >-
          https://$appURL
        location: ApplicationMenu
        text: Event Manager
    EOF
  ignore_errors: true



