#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#       __________  __ ___       _____    ________            
#      / ____/ __ \/ // / |     / /   |  /  _/ __ \____  _____
#     / /   / /_/ / // /| | /| / / /| |  / // / / / __ \/ ___/
#    / /___/ ____/__  __/ |/ |/ / ___ |_/ // /_/ / /_/ (__  ) 
#    \____/_/      /_/  |__/|__/_/  |_/___/\____/ .___/____/  
#                                              /_/            
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing CP4WAIOPS
#
#  CloudPak for Watson AIOps
#
#  ¬©2022 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"




# - name: Show Config
#   debug:
#     var: cp4waiops_cluster
- name: üõ†Ô∏è  SHOW all_config
  debug:
    var: all_config


- name: üõ†Ô∏è  GET global_config
  set_fact: global_config={{ all_config.global_config | default([]) }}
- name: üõ†Ô∏è  SHOW global_config
  debug:
    var: global_config


- name: üõ†Ô∏è  GET _current_openshift_cluster
  set_fact: _current_openshift_cluster={{ all_config.openshift | default([]) }}
- name: üõ†Ô∏è  SHOW _current_openshift_cluster
  debug:
    var: _current_openshift_cluster




# Loop over all clusters
- name: üöÄ Deploy Cloud Pak for Watson AIOps Assets - Loop over Instances for {{current_cp4waiops_cluster.project}}
  include_role:
    name: cp4waiops-install-modules
  loop: "{{ current_cp4waiops_cluster.instances}}"
  loop_control:
    loop_var: current_cp4waiops_feature


