
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#         ________  __  ___     ___    ________       
#        /  _/ __ )/  |/  /    /   |  /  _/ __ \____  _____
#        / // __  / /|_/ /    / /| |  / // / / / __ \/ ___/
#      _/ // /_/ / /  / /    / ___ |_/ // /_/ / /_/ (__  ) 
#     /___/_____/_/  /_/    /_/  |_/___/\____/ .___/____/  
#                                           /_/
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing CP4WAIOPS
#
#  CloudPak for Watson AIOps
#
#  ¬©2022 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Installs:
#
#  - Topology
#    - Create ASM merge rules
#    - Load ASM merge Topology
#    - Create AI Manager Application

# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
 

- name: ‚ú¥Ô∏è ‚ú¥Ô∏è ‚ú¥Ô∏è INSTALLATION MODULE START - {{current_cp4waiops_feature.kind}}
  debug: 
    msg: 
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "                                                                                                                                                   "
    - "      üöÄ CloudPak for Watson AIOps - INSTALLING {{current_cp4waiops_feature.kind}}                                                                                          "
    - "                                                                                                                                                   "
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"





# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INITIALIZATION
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Initialize Logging
- name: üì• Init Logging
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/01_init-logging.yaml"
    

- name: üì• Start Logging
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/90-log-start.yaml"



# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# CHECK FOR INSTALLATION READY
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Check that CP4WAIOPS has been completely installed
- name: üì• Wait for AI Manager to be Ready
  include_tasks: 99_eventmanager-wait-cp4waiops.yaml

# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# CREATE TOPOLOGY
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# - name: Create Topology Observers
#   include_tasks: 41_aimanager-create-observers.yaml
- name: üì• Load Topology Merge Rules
  include_tasks: 10_eventmanager-load-topology-merge.yaml
- name: üì• Create Overlay Topology
  include_tasks: 11_eventmanager-create-topology.yaml
- name: üì• Create Application
  include_tasks: 12_aimanager-create-aiops-application.yaml




- name: üì• End Logging
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/91-log-end.yaml"





- name: ‚úÖ INSTALLATION MODULE DONE - {{current_cp4waiops_feature.kind}}
  debug: 
    msg: 

    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "                                                                                                                                                   "
    - "       ‚úÖ CloudPak for Watson AIOps - DONE INSTALLING {{current_cp4waiops_feature.kind}}                                                                                 "
    - "                                                                                                                                                   "
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
