---
- set_fact:
    _alt_registry_pull_secrets: "{{ all_config.cp_alt_repo.registry_pull_secrets }}"

- debug:
    var: _alt_registry_pull_secrets

- include_tasks: set-alt-registry-pull-secret.yml
  loop: "{{ _alt_registry_pull_secrets | default([]) }}"
  loop_control:
    loop_var: _alt_registry