- name: Create OpenLdap directory for generated files
  ansible.builtin.file:
    path: "{{ openldap_output_directory }}"
    state: directory
    mode: u+rwx

- name: Create Project
  ansible.builtin.include_role:
    name: common
    tasks_from: create-project
  vars:
    common_namespace_name: "{{ openldap_project_name }}"
    common_output_directory: "{{ openldap_output_directory }}"

- name: Prepare yaml file for {{ item }}
  ansible.builtin.template:
    src: "{{ item }}.yaml.j2"
    dest: "{{ openldap_output_directory }}/{{ item }}.yaml"
    mode: u+rwx
  with_items:
    - configmaps
    - secrets
    - persistentvolumeclaims
    - deployments
    - services

- name: Add {{ item.name }}
  kubernetes.core.k8s:
    state: present
    src: "{{ openldap_output_directory }}/{{ item.name }}.yaml"
    wait: true
    wait_sleep: "{{ item.wait_sleep }}"
    wait_timeout: "{{ item.wait_timeout }}"
  with_items:
    - {name: configmaps, wait_sleep: 15, wait_timeout: 15}
    - {name: secrets, wait_sleep: 15, wait_timeout: 15}
    - {name: persistentvolumeclaims, wait_sleep: 15, wait_timeout: 300}
    - {name: deployments, wait_sleep: 15, wait_timeout: 600}
    - {name: services, wait_sleep: 15, wait_timeout: 15}

- name: Set usage entry
  ansible.builtin.include_role:
    name: usage
    tasks_from: set-entry
  vars:
    usage_entry_name: Pre-requisites-OpenLDAP
    usage_entry_value:
      "# OpenLDAP

      As LDAP directory provider.

      ## Endpoints

      - Exposed as NodePort as found in Project *{{ openldap_project_name }}* in Service *openldap*.

      ## Credentials

      - {{ lc_bind_admin_user }} / {{ lc_bind_admin_password }}

      ## Users and Groups

      LDAP contains the following users in {{ lc_ldap_user_base_dn }}.:

      - {{ lc_principal_admin_user }}/{{ lc_principal_admin_password }}

<<<<<<< HEAD
      - cpadmin1/{{ openldap_universal_password }}

      - cpadmin2/{{ openldap_universal_password }}
=======
      - cpmanager1/{{ openldap_universal_password }}

      - cpmanager2/{{ openldap_universal_password }}
>>>>>>> main

      - cpuser/{{ openldap_universal_password }}

      - cpuser1/{{ openldap_universal_password }}

      - cpuser2/{{ openldap_universal_password }}

      LDAP contains the following groups in {{ lc_ldap_group_base_dn }}:

      - {{ lc_principal_admin_group }} - members: {{ lc_ldap_user_id_attribute }}={{ lc_principal_admin_user }},{{ lc_ldap_user_base_dn }}; \
<<<<<<< HEAD
        {{ lc_ldap_user_id_attribute }}=cpadmin1,{{ lc_ldap_user_base_dn }}; {{ lc_ldap_user_id_attribute }}=cpadmin2,{{ lc_ldap_user_base_dn }}

      - cpusers - members: {{ lc_ldap_user_id_attribute }}={{ lc_principal_admin_user }},{{ lc_ldap_user_base_dn }}; \
        {{ lc_ldap_user_id_attribute }}=cpadmin1,{{ lc_ldap_user_base_dn }}; {{ lc_ldap_user_id_attribute }}=cpadmin2,{{ lc_ldap_user_base_dn }}; \
=======
        {{ lc_ldap_user_id_attribute }}=cpmanager1,{{ lc_ldap_user_base_dn }}; {{ lc_ldap_user_id_attribute }}=cpmanager2,{{ lc_ldap_user_base_dn }}

      - cpusers - members: {{ lc_ldap_user_id_attribute }}={{ lc_principal_admin_user }},{{ lc_ldap_user_base_dn }}; \
        {{ lc_ldap_user_id_attribute }}=cpmanager1,{{ lc_ldap_user_base_dn }}; {{ lc_ldap_user_id_attribute }}=cpmanager2,{{ lc_ldap_user_base_dn }}; \
>>>>>>> main
        {{ lc_ldap_user_id_attribute }}=cpuser,{{ lc_ldap_user_base_dn }}; {{ lc_ldap_user_id_attribute }}=cpuser1,{{ lc_ldap_user_base_dn }}; \
        {{ lc_ldap_user_id_attribute }}=cpuser2,{{ lc_ldap_user_base_dn }}

      - cpusers1 - members: {{ lc_ldap_user_id_attribute }}=cpuser,{{ lc_ldap_user_base_dn }}; \
        {{ lc_ldap_user_id_attribute }}=cpuser1,{{ lc_ldap_user_base_dn }}; \
        {{ lc_ldap_user_id_attribute }}=cpuser2,{{ lc_ldap_user_base_dn }}

      ## CLI in OpenLDAP Pod

      ```bash

      #Search for regular attributes

      ldapsearch -x -b \"{{ lc_ldap_base_dn }}\" -H ldap://localhost:1389 -D '{{ lc_bind_admin_user }}' -w {{ lc_bind_admin_password }} \"objectclass=*\"

      #Search for hidden attributes

      ldapsearch -x -b \"{{ lc_ldap_base_dn }}\" -H ldap://localhost:1389 -D '{{ lc_bind_admin_user }}' -w {{ lc_bind_admin_password }} \"objectclass=*\" '+'

      ```

      "
