---
- name: Get OpenShift version
  include_role:
    name: openshift-get-version

- include_tasks: create-icsp.yml
  when: 
  - _mco_exists
  - (all_config.cp_alt_repo | default({})) == {}
  - _p_current_ocp_version < '4.12'

- include_tasks: create-icsp-alt.yml
  when: 
  - _mco_exists
  - (all_config.cp_alt_repo | default({})) != {}
  - _p_current_ocp_version < '4.12'

- include_tasks: create-idms.yml
  when: 
  - _mco_exists
  - (all_config.cp_alt_repo | default({})) == {}
  - _p_current_ocp_version >= '4.12'

- include_tasks: create-idms-alt.yml
  when: 
  - _mco_exists
  - (all_config.cp_alt_repo | default({})) != {}
  - _p_current_ocp_version >= '4.12'

- name: Apply ImageContentSourcePolicy settings if the Machine Config Operator does not exist
  include_tasks: non-mco-apply-icsp.yml
  when: 
  - not _mco_exists
  - (all_config.cp_alt_repo | default({})) == {}