---
# Store password from vault into OpenShift secret (also in case of reinstallation with existing vault secret)
- name: Update {{ cp4d_login_username }} password in OpenShift secret when using Foundational Services IAM
  shell: |
    oc set data --namespace {{ current_cp4d_cluster.project }} ssecret/platform-auth-idp-credentials \
      --from-literal=admin_password="{{ _cp4d_admin_password_vault }}"

- name: Restart the platform identity pods
  shell: |
    oc delete po --namespace {{ current_cp4d_cluster.project }} -l app=platform-auth-service --ignore-not-found
    oc delete po --namespace {{ current_cp4d_cluster.project }} -l app=platform-identity-management --ignore-not-found
    oc delete po --namespace {{ current_cp4d_cluster.project }} -l app=platform-identity-provider --ignore-not-found