# Based on https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/latest?topic=authoring-creating-secrets-protect-sensitive-configuration-data
- name: Add BAWAUT OSs to FNCM Secret
  kubernetes.core.k8s:
    state: present
    api_version: v1
    kind: Secret
    name: ibm-fncm-secret
    namespace: "{{ cp4ba_project_name }}"
    definition: |
      data:
        {{ item }}DBUsername: {{ item | b64encode }}
        {{ item }}DBPassword: {{ cp4ba_postgresql_universal_password | b64encode }}
  with_items:
    - bawdocs
    - bawtos
    - bawdos

- name: Add BAWAUT OSs to FNCM Secret
  kubernetes.core.k8s:
    state: present
    api_version: v1
    kind: Secret
    name: ibm-fncm-secret
    namespace: "{{ cp4ba_project_name }}"
    definition: |
      data:
        chDBUsername: {{ 'chdb' | b64encode }}
        chDBPassword: {{ cp4ba_postgresql_universal_password | b64encode }}

# Based on https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/latest?topic=services-optional-customizing-runtime-server-properties
# Based on https://www.ibm.com/docs/en/baw/20.x?topic=work-configuring-email-notifications
# Based on https://www.ibm.com/docs/en/baw/20.x?topic=configuration-creating-100customxml-file
- name: Prepare yaml file for BAWAUT Lombardi Custom100.xml Secret
  ansible.builtin.template:
    src: bawaut/bawaut-lombardi-custom-xml-secret.yaml.j2
    dest: "{{ cp4ba_output_directory }}/bawaut-lombardi-custom-xml-secret.yaml"
    mode: u+rwx

- name: Add BAWAUT Lombardi Custom100.xml Secret
  kubernetes.core.k8s:
    state: present
    src: "{{ cp4ba_output_directory }}/bawaut-lombardi-custom-xml-secret.yaml"
