# Based on https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/latest?topic=insights-customizing-kafka-elasticsearch-server-configuration
# Based on https://www.ibm.com/docs/en/cloud-paks/1.0?topic=p-system-requirements
# Based on https://github.com/IBM/automation/tree/main/cr-examples/AutomationBase
# Based on https://www.ibm.com/docs/en/cloud-paks/1.0?topic=foundation-custom-resources#automationbase
- name: Prepare yaml file for IAF Issuer
  ansible.builtin.template:
    src: iaf/iaf-issuer.yaml.j2
    dest: "{{ cp4ba_output_directory }}/iaf-issuer.yaml"
    mode: u+rwx

- name: Add IAF Issuer
  kubernetes.core.k8s:
    state: present
    force: false
    merge_type: merge
    src: "{{ cp4ba_output_directory }}/iaf-issuer.yaml"

- name: Prepare yaml file for Global CA certificate Secret
  ansible.builtin.template:
    src: iaf/global-ca-secret.yaml.j2
    dest: "{{ cp4ba_output_directory }}/global-ca-secret.yaml"
    mode: u+rwx

- name: Add Global CA crt Secret
  kubernetes.core.k8s:
    state: present
    force: false
    merge_type: merge
    src: "{{ cp4ba_output_directory }}/global-ca-secret.yaml"

# Based on https://www.ibm.com/docs/en/cloud-paks/1.0?topic=configuration-operational-datastore
# Username change is not described
- name: Prepare yaml file for IAF admin ES user Secret
  ansible.builtin.template:
    src: iaf/es-secret.yaml.j2
    dest: "{{ cp4ba_output_directory }}/es-secret.yaml"
    mode: u+rwx

- name: Add IAF admin ES user Secret
  kubernetes.core.k8s:
    state: present
    force: false
    merge_type: merge
    src: "{{ cp4ba_output_directory }}/es-secret.yaml"

- name: Prepare yaml file for AutomationBase CR
  ansible.builtin.template:
    src: iaf/automationbase.yaml.j2
    dest: "{{ cp4ba_output_directory }}/automationbase.yaml"
    mode: u+rwx

- name: Add AutomationBase CR
  kubernetes.core.k8s:
    state: present
    force: false
    merge_type: merge
    src: "{{ cp4ba_output_directory }}/automationbase.yaml"

- name: Wait for AutomationBase instance Ready state
  ansible.builtin.include_role:
    name: common
    tasks_from: wait-resource-condition
  vars:
    common_api_version: base.automation.ibm.com/v1beta1
    common_resource_kind: AutomationBase
    common_resource_name: foundation-iaf
    common_resource_namespace: "{{ cp4ba_project_name }}"
    common_condition_name: Ready
    common_retries: 30
    common_delay: 60

- name: Wait for Apicurio Deployment to be Available
  ansible.builtin.include_role:
    name: common
    tasks_from: wait-resource-condition
  vars:
    common_api_version: v1
    common_resource_kind: Deployment
    common_resource_name: iaf-system-apicurio
    common_resource_namespace: "{{ cp4ba_project_name }}"
    common_condition_name: Available
    common_retries: 80
    common_delay: 15

- name: Wait for KafkaUser CRD to be Established
  ansible.builtin.include_role:
    name: common
    tasks_from: wait-crd
  vars:
    common_crd_name: kafkausers.ibmevents.ibm.com

- name: Prepare yaml file for KafkaUser Secret
  ansible.builtin.template:
    src: iaf/kafkauser-secret.yaml.j2
    dest: "{{ cp4ba_output_directory }}/kafkauser-secret.yaml"
    mode: u+rwx

- name: Add KafkaUser Secret
  kubernetes.core.k8s:
    state: present
    force: false
    merge_type: merge
    src: "{{ cp4ba_output_directory }}/kafkauser-secret.yaml"

# Based on https://www.ibm.com/docs/en/cloud-paks/1.0?topic=foundation-administration-guide#day-2-operations-for-kafka reference for Strimzi in Kafka Day 2
- name: Prepare yaml file for KafkaUser CR
  ansible.builtin.template:
    src: iaf/kafkauser.yaml.j2
    dest: "{{ cp4ba_output_directory }}/kafkauser.yaml"
    mode: u+rwx

- name: Add KafkaUser CR
  kubernetes.core.k8s:
    state: present
    force: false
    merge_type: merge
    src: "{{ cp4ba_output_directory }}/kafkauser.yaml"

- name: Wait for KafkaUser instance Ready state
  ansible.builtin.include_role:
    name: common
    tasks_from: wait-resource-condition
  vars:
    common_api_version: ibmevents.ibm.com/v1beta2
    common_resource_kind: KafkaUser
    common_resource_name: "{{ principal_admin_user }}"
    common_resource_namespace: "{{ cp4ba_project_name }}"
    common_condition_name: Ready
    common_retries: 80
    common_delay: 15
