---
- name: Ensure the status log folder exists
  file:
    path: "{{status_dir}}/log"
    state: directory

- name: Delete IPI cluster, logs can be found in {{ status_dir }}/log/{{ _current_openshift_cluster.name }}-delete-cluster.log
  shell: |
    openshift-install destroy cluster --dir={{ status_dir }}/aws-ipi/{{ _current_openshift_cluster.name }} >> {{ status_dir }}/log/{{ _current_openshift_cluster.name }}-delete-cluster.log 2>&1
  environment:
    AWS_ACCESS_KEY_ID: "{{ _aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ _aws_secret_access_key }}"

- name: Delete "{{ _current_openshift_cluster.name }}-kubeadmin-password" secret from the vault
  include_role:
    name: vault-delete-secret
  vars:
    secret_name: "{{ _current_openshift_cluster.name }}-kubeadmin-password"
    secret_group: "{{ environment_name }}"