- name: Remove obsolete cartridges from CP4D cluster {{ _p_current_cp4d_cluster.project }}
  debug:
    msg: "Remove obsolete cartridges from CP4D cluster {{ _p_current_cp4d_cluster.project }}"

- name: Check which obsolete cartridges are still installed
  include_tasks: cp4d-remove-cr.yml
  loop: "{{ cartridge_cr }}"
  loop_control:
    loop_var: _current_cartridge_cr
