---
- name: Connect to private image registry
  include_role: 
    name: connect-private-image-registry
  vars:
    _p_current_cp4d_cluster: "{{ current_cp4d_cluster }}"

- name: Create ImageContentSourcePolicy for the Cloud Pak with private registry
  include_role:
    name: cp-ocp-icsp