---
openshift:
- name: {{ env_id }}-cluster
  azure_aro_name: {{ env_id }}-infra
  subdomain_name: {{ env_id }}
  network:
    pod_cidr: "10.128.0.0/14"
    service_cidr: "172.30.0.0/16"
  openshift_storage:
  - storage_name: ocs-storage
    storage_type: ocs
    ocs_storage_label: ocs
    ocs_storage_size_gb: 512
    ocs_dynamic_storage_class: managed-premium
