---
- name: Get Route to Cloud Pak for Data
  shell: |
    oc --namespace {{ current_cp4d_cluster.project }} get route -l component=ibm-nginx \
      -o jsonpath="{.items[0].spec.host}"
  register: cp4d_url

- name: Get ZenService CR to check authentication method
  shell: |
    oc get --namespace {{ current_cp4d_cluster.project }} ZenService lite-cr -o json
  register: _zenservice_cr

- set_fact:
    _iam_integration: "{{ (_zenservice_cr.stdout | from_json).spec.iamIntegration | bool  }}"

- set_fact:
    _cp4d_admin_user: "admin"

- set_fact:
    _cp4d_admin_user: "cpadmin"
  when: _iam_integration

- set_fact:
    cp4d_admin_password_vault_key_name: "cp4d_admin_{{ current_cp4d_cluster.project| replace('-','_') }}_{{ current_cp4d_cluster.openshift_cluster_name| replace('-','_') }}"

- name: Get admin password {{ cp4d_admin_password_vault_key_name }} from the vault
  include_role: 
    name: vault-get-secret
  vars:
    secret_name: "{{ cp4d_admin_password_vault_key_name }}"
    secret_group: "{{ environment_name }}"
    _p_secret_variable: _cp4d_admin_password

- name: Get admin API key {{ current_cp4d_cluster.project }}-{{ _cp4d_admin_user }}-api-key from the vault
  include_role: 
    name: vault-get-secret
  vars:
    secret_name: "{{ current_cp4d_cluster.project }}-{{ _cp4d_admin_user }}-api-key"
    secret_group: "{{ environment_name }}"
    _p_secret_variable: _cp4d_admin_api_key

- name: Make sure that directory {{ status_dir }}/cloud-paks exists
  file:
    path: "{{ status_dir }}/cloud-paks"
    state: directory

- name: Write Cloud Pak for Data info to {{ status_dir }}/cloud-paks/cloud-pak-deployer-info.txt
  blockinfile:
    path: "{{ status_dir }}/cloud-paks/cloud-pak-deployer-info.txt"
    create: True
    insertafter: EOF
    marker: "--- Cloud Pak for Data project {{ current_cp4d_cluster.project }} ---"
    block: |2
      {{ lookup('template','cp4d-info.j2') }}