---
- name: Loop through each watsonx.ai foundation model inference server to check if it must be deleted
  include_tasks: delete-watsonx_ai-instance.yml
  loop: "{{ _configured_watsonxai_instances }}"
  loop_control:
    loop_var: _watsonx_ai_instance