---
cp4d:

- project: cpd
  openshift_cluster_name: "{{ env_id }}"
  cp4d_version: 5.1.1
  olm_utils: False
  use_case_files: True
  accept_licenses: False
  cartridges:
  - name: cp-foundation
    scale: level_1
    license_service:
      state: disabled
      threads_per_core: 2
  
  - name: lite

  - name: scheduler 
    state: removed
    
#
# All tested cartridges. To install, change the "state" property to "installed". To uninstall, change the state
# to "removed" or comment out the entire cartridge. Make sure that the "-" and properties are aligned with the lite
# cartridge; the "-" is at position 3 and the property starts at position 5.
#
# If a cartridge has dependencies and you want to install it, you must ensure that the dependent cartridge is also
# installed.
#

  - name: analyticsengine 
    description: Analytics Engine Powered by Apache Spark 
    size: small 
    state: removed

  - name: bigsql
    description: Db2 Big SQL
    state: removed

  - name: ca
    description: Cognos Analytics
    size: small
    instances:
    - name: ca-instance
      metastore_ref: ca-metastore
    state: removed

  - name: cde
    description: Cognos Dashboards
    state: removed

  - name: datagate
    description: Db2 Data Gate
    state: removed

  - name: datastage-ent-plus
    description: DataStage Enterprise Plus
    state: removed

    # The default instance is created automatically with the DataStage installation. If you want to create additional instances
    # uncomment the section below and specify the various scaling options.

    # instances:
    #   - name: ds-instance
    #     # Optional settings
    #     description: "datastage ds-instance"
    #     size: medium
    #     storage_class: efs-nfs-client
    #     storage_size_gb: 60
    #     # Custom Scale options
    #     scale_px_runtime:
    #       replicas: 2
    #       cpu_request: 500m
    #       cpu_limit: 2
    #       memory_request: 2Gi
    #       memory_limit: 4Gi
    #     scale_px_compute:
    #       replicas: 2
    #       cpu_request: 1
    #       cpu_limit: 3
    #       memory_request: 4Gi
    #       memory_limit: 12Gi    

  - name: db2
    description: Db2 OLTP
    size: small
    instances:
    - name: ca-metastore
      metadata_size_gb: 20
      data_size_gb: 20
      backup_size_gb: 20  
      transactionlog_size_gb: 20
    state: removed

  - name: db2wh
    description: Db2 Warehouse
    state: removed

  - name: dmc
    description: Db2 Data Management Console
    state: removed

  - name: dods
    description: Decision Optimization
    size: small
    state: removed

  - name: dp
    description: Data Privacy
    size: small
    state: removed

  - name: dv
    description: Data Virtualization
    size: small 
    instances:
    - name: data-virtualization
    state: removed

  # Please note that for EDB Postgress, a secret edb-postgres-license-key must be created in the vault
  # before deploying
  - name: edb_cp4d
    description: EDB Postgres
    state: removed
    instances:
      - name: instance1
        version: "13.5"
        #type: Standard
        #members: 1
        #size_gb: 50
        #resource_request_cpu: 1000m
        #resource_request_memory: 4Gi
        #resource_limit_cpu: 1000m
        #resource_limit_memory: 4Gi

  - name: hadoop
    description: Execution Engine for Apache Hadoop
    size: small
    state: removed

  - name: match360
    description: IBM Match 360
    size: small
    wkc_enabled: true
    state: removed

  - name: openpages
    description: OpenPages
    state: removed

  # For Planning Analytics, the case version is needed due to defect in olm utils
  - name: planning-analytics
    description: Planning Analytics
    case_version: 4.0.90573
    state: removed

  - name: rstudio
    description: RStudio Server with R 3.6
    size: small
    state: removed

  - name: spss
    description: SPSS Modeler
    state: removed

  - name: voice-gateway
    description: Voice Gateway
    replicas: 1
    state: removed

  - name: watson-assistant
    description: Watson Assistant
    size: small
    state: removed

  - name: watson-discovery
    description: Watson Discovery
    state: removed

  # For Watson Knowledge Studio, the case version is needed due to defect in olm utils
  - name: watson-ks
    description: Watson Knowledge Studio
    case_version: 4.0.9
    size: small
    state: removed

  - name: watson-openscale
    description: Watson OpenScale
    size: small
    state: removed

  - name: watson-speech
    description: Watson Speech (STT and TTS)
    stt_size: xsmall
    tts_size: xsmall
    state: removed

  - name: wkc
    description: Watson Knowledge Catalog
    size: small
    state: removed

  - name: wml
    description: Watson Machine Learning
    size: small
    state: installed

  - name: wml-accelerator
    description: Watson Machine Learning Accelerator
    replicas: 1
    size: small
    state: removed

  - name: wsl
    description: Watson Studio
    state: installed

  - name: ws-runtimes
    description: Watson Studio Runtimes
    runtimes:
    - ibm-cpd-ws-runtime-py39gpu
    - ibm-cpd-ws-runtime-r36
    state: removed

#
# Cartridges where extra work is needed (will not install automatically)
# 
  # Product Master requires set up of the Db2 instance secret before install
  - name: productmaster
    description: Product Master
    size: small  
    state: removed