---
- set_fact:
    _case_save_command: "{{ lookup('template','case-save-command.j2') }}"

- name: Show case save command
  debug:
    var: _case_save_command

- name: Save case file {{ current_cp4waiops_feature.case_name }}-{{ current_cp4waiops_feature.case_version }}
  shell: |
    {{ _case_save_command }}
  register: _case_save
  retries: 5
  delay: 5
  until: _case_save.rc==0