---
cp4d:

- project: zen-40
  openshift_cluster_name: {{ env_id }}
  cp4d_version: 4.0
  use_case_files: True
  cartridges:
  - name: cp-foundation
    license_service:
      state: disabled
      threads_per_core: 2
    case_version: 1.11.0
  - name: lite
    subscription_channel: v2.0
    case_version: 2.0.10

#
# All tested cartridges. To install, change the "state" property to "installed". To uninstall, change the state
# to "removed" or comment out the entire cartridge. Make sure that the "-" and properties are aligned with the lite
# cartridge; the "-" is at position 3 and the property starts at position 5.
#
# If a cartridge has dependencies and you want to install it, you must ensure that the dependent cartridge is also
# installed.
#

  - name: analyticsengine 
    version: 4.0.6
    subscription_channel: stable-v1
    case_version: 4.0.6
    size: small 
    state: removed

  - name: bigsql
    version: 7.2.6
    subscription_channel: v7.2
    case_version: 7.2.6
    state: removed

  - name: ca
    version: 4.0.6
    subscription_channel: v4.0
    case_version: 4.0.8
    size: small
    instances:
    - name: ca-instance
      metastore_ref: ca-metastore
    state: removed

  - name: cde
    version: 4.0.6
    subscription_channel: v1.0
    case_version: 2.0.6
    state: removed

  - name: datagate
    version: 2.0.6
    subscription_channel: v2.0
    case_version: 4.0.6
    state: removed

  - name: datastage
    version: 4.0.6
    subscription_channel: v1.0
    case_version: 4.0.7
    state: removed

  - name: db2
    version: 4.0.8
    subscription_channel: v1.0
    case_version: 4.0.8
    size: small
    instances:
    - name: ca-metastore
      metadata_size_gb: 20
      data_size_gb: 20
      backup_size_gb: 20  
      transactionlog_size_gb: 20
    state: removed

  - name: db2u
    version: 4.0.8
    subscription_channel: v1.1
    case_version: 4.0.8
    state: removed

  - name: db2wh
    version: 4.0.8
    subscription_channel: v1.0
    case_version: 4.0.8
    state: removed

  - name: dmc
    version: 4.0.6
    subscription_channel: v1.0
    case_version: 4.0.6
    state: removed

  - name: dods
    version: 4.0.6
    subscription_channel: v4.0
    case_version: 4.0.6
    size: small
    dependencies:
    - name: wsl
    - name: wml
    state: removed

  - name: dp
    version: 4.0.6
    subscription_channel: v1.0
    case_version: 4.0.6
    size: small
    state: removed

  - name: dv
    version: 1.7.6
    subscription_channel: v1.7
    case_version: 1.7.6
    size: small 
    dependencies:
    - name: db2u
    instances:
    - name: data-virtualization
    state: removed

  - name: hadoop
    version: 4.0.6
    size: small
    subscription_channel: v1.0
    case_version: 4.0.7
    dependencies:
    - name: wsl
    state: removed

  - name: mdm
    version: 1.1.188
    subscription_channel: v1.1
    case_version: 1.0.182
    size: small
    wkc_enabled: true
    state: removed

  - name: openpages
    version: 8.204.3
    subscription_channel: v1.0
    case_version: 2.1.3+20220205.003421.82040223
    state: removed

  - name: planning-analytics
    version: 4.0.6
    subscription_channel: v4.0
    case_version: 4.0.60476
    state: removed

  - name: rstudio
    version: 4.0.6
    subscription_channel: v1.0
    case_version: 1.0.6
    size: small
    dependencies:
    - name: wsl
    state: removed

  - name: spss
    version: 4.0.6
    subscription_channel: v1.0
    case_version: 1.0.6
    dependencies:
    - name: wsl
    state: removed

  - name: voice-gateway
    version: 1.0.7
    subscription_channel: v1.0
    case_version: 1.0.5
    replicas: 1
    state: removed

  - name: watson-assistant
    version: 4.0.6
    subscription_channel: v4.0
    case_version: 4.0.6
    size: small
    state: removed

  - name: watson-discovery
    version: 4.0.6
    subscription_channel: v4.0
    case_version: 4.0.6
    state: removed

  - name: watson-ks
    version: 4.0.5
    subscription_channel: v4.0
    case_version: 4.0.5
    size: small
    state: removed

  - name: watson-openscale
    version: 4.0.6
    subscription_channel: v1.5
    case_version: 2.5.1
    size: small
    state: removed

  - name: watson-speech
    version: 4.0.6
    subscription_channel: v4.0
    case_version: 4.0.7
    stt_size: xsmall
    tts_size: xsmall
    state: removed

  - name: wkc
    version: 4.0.6
    subscription_channel: v1.0
    case_version: 4.0.6
    size: small
    state: removed

  - name: wml
    version: 4.0.6
    subscription_channel: v1.1
    case_version: 4.0.7
    size: small
    state: installed

  - name: wml-accelerator
    version: 2.3.6
    subscription_channel: v1.0
    case_version: 2.3.6
    replicas: 1
    size: small
    state: removed

  - name: wsl
    version: 4.0.6
    subscription_channel: v2.0
    case_version: 2.0.6
    state: installed

#
# Cartridges where extra work is needed (will not install automatically)
# 
  # Product Master requires set up of the Db2 instance secret before install
  - name: productmaster
    version: 1.0.3
    subscription_channel: v1.0
    size: small  
    case_version: 1.0.3
    state: removed