---

# Create or update daemonset to update pull secret for nodes
- name: Create temporary directory to hold current global pull secret content
  tempfile:
    state: directory
  register: pull_secret_dir
- name: Extract the global pull secret
  shell: |
    oc extract secret/pull-secret -n openshift-config --confirm --to={{ pull_secret_dir.path }}
- name: Create secret for DaemonSet
  shell: |
    if ! oc get secret -n kube-system cloud-pak-pull-secret;then
      oc create secret generic cloud-pak-pull-secret -n kube-system > /dev/null 2>&1
    fi
- name: Set data for secret
  shell: |
    oc set data secret/cloud-pak-pull-secret -n kube-system \
      --from-file=newdockerconfigjson={{ pull_secret_dir.path }}/.dockerconfigjson
- name: Generate DaemonSet to set the current pull secret for all nodes
  template:
    src: cloud-pak-pull-secret-ds.j2
    dest: "{{ cloud_pak_prepare_ocp_temp_dir.path }}/cloud-pak-pull-secret-ds.yaml"
- name: Create or replace DaemonSet cloud-pak-pull-secret-ds
  shell: |
    if oc get ds -n kube-system cloud-pak-pull-secret-ds;then
      oc delete ds -n kube-system cloud-pak-pull-secret-ds
    fi
    oc apply -f {{ cloud_pak_prepare_ocp_temp_dir.path }}/cloud-pak-pull-secret-ds.yaml