---
# Determine if any cartridges require kubeletconfig to be set
- set_fact:
    _db2u_kubelet: False

- name: Determine if any of the cartridges require kubelet configuration
  set_fact:
    _db2u_kubelet: "{{ _db2u_kubelet or (item.db2u_kubelet | default(False)) }}"
  when: (item.state | default('installed')) == 'installed'
  loop: "{{ _cartridges_to_install }}"
  no_log: True

- name: Show if cartridges require kubelet configuration
  debug:
    var: _db2u_kubelet