---
- name: Make sure old deployer-state.out does not exist
  file:
    path: "{{ status_dir }}/log/deployer-state.out"
    state: absent

- name: Starting background task to record deployer state in {{ status_dir }}/log
  shell: |
    {{ role_path }}/files/record-deployer-state.sh \
      {{ status_dir }} {{ _p_state_interval }}
  async: 86400
  poll: 0
  register: _record_deployer_state

- name: Show details of background task to record deployer state
  debug:
    var: _record_deployer_state