- name: Create OpenLdap directory for generated files
  ansible.builtin.file:
    path: "{{ phpldapadmin_output_directory }}"
    state: directory
    mode: u+rwx

- name: Create Project
  ansible.builtin.include_role:
    name: common
    tasks_from: create-project
  vars:
    common_namespace_name: "{{ phpldapadmin_project_name }}"
    common_output_directory: "{{ phpldapadmin_output_directory }}"

- name: Prepare yaml file for {{ item }}
  ansible.builtin.template:
    src: "{{ item }}.yaml.j2"
    dest: "{{ phpldapadmin_output_directory }}/{{ item }}.yaml"
    mode: u+rwx
  with_items:
    - configmaps
    - serviceaccounts
    - rolebindings
    - deployments
    - services

- name: Add {{ item.name }}
  kubernetes.core.k8s:
    state: present
    src: "{{ phpldapadmin_output_directory }}/{{ item.name }}.yaml"
    wait: true
    wait_sleep: "{{ item.wait_sleep }}"
    wait_timeout: "{{ item.wait_timeout }}"
  with_items:
    - {name: configmaps, wait_sleep: 15, wait_timeout: 15}
    - {name: serviceaccounts, wait_sleep: 15, wait_timeout: 15}
    - {name: rolebindings, wait_sleep: 15, wait_timeout: 15}
    - {name: deployments, wait_sleep: 15, wait_timeout: 600}
    - {name: services, wait_sleep: 15, wait_timeout: 15}

- name: Get OCP Apps Endpoint
  ansible.builtin.include_role:
    name: common
    tasks_from: apps-endpoint
  vars:
    common_output_to_var: "apps_endpoint_domain"
  when: apps_endpoint_domain is not defined

- name: Crete Edge Route
  ansible.builtin.include_role:
    name: common
    tasks_from: create-edge-route
  vars:
    common_namespace_name: "{{ phpldapadmin_project_name }}"
<<<<<<< HEAD
    common_route_name: "phpldapadmin-{{ phpldapadmin_project_name }}"
=======
    common_route_name: phpldapadmin
>>>>>>> main
    common_service_name: phpldapadmin
    common_apps_endpoint_domain: "{{ apps_endpoint_domain }}"
    common_output_directory: "{{ phpldapadmin_output_directory }}"

- name: Set usage entry
  ansible.builtin.include_role:
    name: usage
    tasks_from: set-entry
  vars:
    usage_entry_name: Extras-phpLDAPadmin
    usage_entry_value:
      "# phpLDAPadmin

      As LDAP management tool.

      ## Endpoints

      - PHP LDAP admin management console: https://phpldapadmin-{{ phpldapadmin_project_name }}.{{ apps_endpoint_domain }}/

      ## Credentials

      - {{ lc_bind_admin_user }} / {{ lc_bind_admin_password }}

      "
