---

- name: Delete Secret from Vault Hashicorp
  block:
    - name: Validate mandatory variables are defined for Hashicorp Vault
      assert:
        that:
          - vault_secret_path is defined
          - secret_name is defined
          - secret_group is defined

    - set_fact:
        _hashicorp_secret_name_path: "{{ vault_secret_path }}/{{ secret_group}}/{{ secret_name }}"
      when: (vault_secret_path_append_group | default(True))

    - set_fact:
        _hashicorp_secret_name_path: "{{ vault_secret_path }}/{{ secret_name }}"
      when: not (vault_secret_path_append_group | default(True))

    - name: Delete Secret Hashicorp vault (API Key)
      include_tasks: delete-secret-hashicorp-api-key.yml
      vars:
        hashicorp_vault_address: "{{ vault_url }}"
        hashicorp_secret_name_path: "{{ _hashicorp_secret_name_path }}"
      when: vault_authentication_type == 'api-key'

    - name: Delete Secret Hashicorp vault (Certificate)
      include_tasks: delete-secret-hashicorp-certificate.yml
      vars:
        hashicorp_vault_address: "{{ vault_url }}"
        hashicorp_secret_name_path: "{{ _hashicorp_secret_name_path }}"
      when: vault_authentication_type == 'certificate'      
  when: "vault_type == 'hashicorp-vault'"

- name: Delete Secret from Vault IBM Cloud
  block:
    - name: Validate mandatory variables are defined for Vault IBM Cloud
      assert:
        that:
          - secret_name is defined
          - secret_group is defined

    - name: Delete secret from Vault IBMCloud
      include_tasks: delete-secret-ibmcloud.yml
      vars:
        ibmcloud_vault_address: "{{ vault_url }}"
        ibm_cloud_secret_name: "{{ secret_name }}"
  when: "vault_type == 'ibmcloud-vault'"

- name: Delete Secret from Vault file
  block:
    - name: Validate mandatory variables are defined for Vault file
      assert:
        that:
          - secret_name is defined

    - name: Get secret in Vault file
      include_tasks: delete-secret-file.yml
  when: "vault_type == 'file-vault'"

- name: Secret {{ secret_group }}/{{ secret_name }} was deleted
  debug:
    msg: ""
  vars:
    ansible_callback_diy_runner_on_ok_msg: |+2
      Secret {{ secret_group }}/{{ secret_name }} was deleted