---
- name: Find file holding vault configuration
  find:
    paths: "{{ config_dir }}/config"
    patterns: "*.yaml"
    file_type: file
    contains: 'vault:'
    recurse: False
    follow: True
  register: _found_vault_config_file

- debug:
    var: _found_vault_config_file

- name: Load yaml file into variables
  include_vars:
    file: "{{ (_found_vault_config_file.files | first).path }}"
  when: _found_vault_config_file.matched != 0

- name: Read vault config
  include_tasks: read-vault-config.yml
  when: vault | default({}) != {}

- set_fact:
    vault_type: "file-vault"
  when: vault_type is not defined

- set_fact:
    vault_authentication_type: "none"
  when: vault_authentication_type is not defined