
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Install ADDONS
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

# --------------------------------------------------------------------------------------------------------------------------------------
# Create OCP Demouser Account
# --------------------------------------------------------------------------------------------------------------------------------------

- name: ğŸ›°ï¸  START - CREATE USER
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"


- name: Log
  shell: |
    export MESSAGE="Creating OCP User"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_cp4waiops_feature.kind}}.log
    echo $currentDate" - "$MESSAGE  >> ../install_{{current_cp4waiops_feature.kind}}.log
  ignore_errors: true



- name: ğŸ‘©â€ğŸ’» DEMO USER - Check OCP Demouser Account
  shell: |
    oc get serviceaccount --ignore-not-found -n default demo-admin
  ignore_errors: true
  register: USER_EXISTS


- name: ğŸ‘©â€ğŸ’» DEMO USER - Create OCP Demouser Account
  shell: |
        export WAIOPS_NAMESPACE=$(oc get po -A|grep aiops-orchestrator-controller |awk '{print$1}')
        oc project $WAIOPS_NAMESPACE 
        oc create serviceaccount -n default demo-admin
        oc create clusterrolebinding test-admin --clusterrole=cluster-admin --serviceaccount=default:demo-admin
        oc create clusterrolebinding ibm-zen-operator-serviceaccount --clusterrole=cluster-admin --serviceaccount=ibm-common-services:ibm-zen-operator-serviceaccount
  ignore_errors: true
  register: demo_account
  when: USER_EXISTS.stdout|length == 0

