

- name: ðŸ›°ï¸  START - LOAD SNOW TRAINING DATA
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"

- name: Log
  shell: |
    export MESSAGE="Load SNOW Training Data into ElasticSearch"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_cp4waiops_feature.kind}}.log
    echo $currentDate" - "$USER" - "$MESSAGE  >> ../install_{{current_cp4waiops_feature.kind}}.log
  ignore_errors: yes



- name: ðŸ“¥ TRAINING LOAD SNOW - CREATE CLUSTERROLE
  kubernetes.core.k8s:
    state: present
    namespace: default
    src: ./templates/training/default-clusterrole.yaml
    

- name: ðŸ“¥ TRAINING LOAD SNOW - LOAD ELASTICSEARCH SNOW DATA 
  kubernetes.core.k8s:
    state: present
    namespace: default
    template: ./templates/training/load-job-snow.j2
  