- name: üõ∞Ô∏è  START - CREATE METRICS ANALYSIS DEFINITIONS
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"



- name: Log
  shell: |
    export MESSAGE="Create Metric Anomaly Training Definition"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_cp4waiops_feature.kind}}.log
    echo $currentDate" - "$MESSAGE  >> ../install_{{current_cp4waiops_feature.kind}}.log
  ignore_errors: true



- name: üöÄ TRAINING CREATE METRICS - CREATE METRICS ANALYSIS CONFIGURATION
  shell: |
    set -x
    export ROUTE=""
    pwd

    echo "***************************************************************************************************************************************************"
    echo "   üõ†Ô∏è   Create Analysis Definiton: Metric Anomaly"
    export FILE_NAME=create-analysis-METRIC{{current_cp4waiops_feature.training_suffix | default("") }}.graphql
    export FILE_PATH="{{role_path}}/templates/training/training-definitions/"
    {{role_path}}/templates/training/scripts/execute-graphql.sh




  register: output_string
  ignore_errors: true
  args:
    executable: /bin/bash


- name: üü£ TRAINING CREATE METRICS - RESULT
  debug: 
    var: output_string.stdout_lines
    #verbosity: 1
