
- name: üõ∞Ô∏è  START - CREATE SNOW ANALYSIS DEFINITIONS
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"



- name: Log
  shell: |
    export MESSAGE="Create SNOW Training Definition"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_cp4waiops_feature.kind}}.log
    echo $currentDate" - "$USER" - "$MESSAGE  >> ../install_{{current_cp4waiops_feature.kind}}.log
  ignore_errors: yes




- name: üöÄ TRAINING CREATE SNOW - CREATE SNOW CONFIGURATION
  shell: |
    set -x
    export ROUTE=""

    pwd

    echo "***************************************************************************************************************************************************"
    echo "   üõ†Ô∏è   Create Analysis Definiton: Change Risk"
    export FILE_NAME=create-analysis-CR.graphql
    export FILE_PATH="{{role_path}}/templates/training/training-definitions/"
    {{role_path}}/templates/training/scripts/execute-graphql.sh

    echo "***************************************************************************************************************************************************"
    echo "   üõ†Ô∏è   Create Analysis Definiton: Similar Incidents"
    export FILE_NAME=create-analysis-SI.graphql
    export FILE_PATH="{{role_path}}/templates/training/training-definitions/"
    {{role_path}}/templates/training/scripts/execute-graphql.sh



  register: output_string
  ignore_errors: yes
  args:
    executable: /bin/bash



- name: üü¢ TRAINING CREATE SNOW - RESULT
  debug: 
    var: output_string.stdout_lines
  #when: PRINT_LOGINS == true

