- name: üõ∞Ô∏è  START - RUN LOG TRAINING
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"



- name: Log
  shell: |
    export MESSAGE="Run LAD Training"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_cp4waiops_feature.kind}}.log
    echo $currentDate" - "$MESSAGE  >> ../install_{{current_cp4waiops_feature.kind}}.log
  ignore_errors: true


- name: üöÄ TRAINING RUN - RUN TRAINING LAD
  shell: |
    set -x
    
    echo "  ***************************************************************************************************************************************************"
    echo "   üõ†Ô∏è   Run Analysis: Log Anomaly Detection"
    export FILE_NAME=run-analysis-LAD.graphql
    export FILE_PATH="{{role_path}}/templates/training/training-definitions/"
    {{role_path}}/templates/training/scripts/execute-graphql.sh

  register: output_string
  ignore_errors: true
  args:
    executable: /bin/bash


- name: üü£ TRAINING RUN - RESULT
  debug: 
    var: output_string.stdout_lines
    #verbosity: 1

