- name: Create directory for generated files
  ansible.builtin.file:
    path: "{{ mail_output_directory }}"
    state: directory
    mode: u+rwx

- name: Mock variables
  ansible.builtin.set_fact:
    _tls_key: mock
    _tls_crt: mock

- name: Prepare yaml file for {{ item }}
  ansible.builtin.template:
    src: "{{ item }}.yaml.j2"
    dest: "{{ mail_output_directory }}/{{ item }}.yaml"
    mode: u+rwx
  with_items:
    - serviceaccounts
    - rolebindings
    - configmaps
    - secrets
    - statefulsets
    - services

- name: Remove {{ item.name }}
  kubernetes.core.k8s:
    state: absent
    src: "{{ mail_output_directory }}/{{ item.name }}.yaml"
    wait: true
    wait_sleep: "{{ item.wait_sleep }}"
    wait_timeout: "{{ item.wait_timeout }}"
  with_items:
    - {name: services, wait_sleep: 15, wait_timeout: 15}
    - {name: statefulsets, wait_sleep: 15, wait_timeout: 600}
    - {name: secrets, wait_sleep: 15, wait_timeout: 15}
    - {name: configmaps, wait_sleep: 15, wait_timeout: 15}
    - {name: rolebindings, wait_sleep: 15, wait_timeout: 15}
    - {name: serviceaccounts, wait_sleep: 15, wait_timeout: 15}

- name: Remove PersistentVolumeClaims
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: PersistentVolumeClaim
    label_selectors:
      - app = mail
    namespace: "{{ mail_project_name }}"
    wait: true
    wait_sleep: 15
    wait_timeout: 120

- name: Remove Empty Project
  ansible.builtin.include_role:
    name: common
    tasks_from: remove-empty-project
  vars:
    common_project_name: "{{ mail_project_name }}"
