---
- name: Get secret Validate mandatory variables are defined
  assert:
    that:
      - secret_group is defined
      - secret_name is defined

- name: Create directory {{ status_dir }}/vault if not existent
  file:
    path: "{{ status_dir }}/vault"
    state: directory

- name: Create file-vault file {{ status_dir }}/vault/{{ secret_group }} if not existent
  file:
    path: "{{ status_dir }}/vault/{{ secret_group }}"
    state: touch

- set_fact:
    secret_value: "{{ lookup('ini', secret_name + ' type=properties file=' + status_dir + '/vault/' + secret_group) }}"

- set_fact:
    has_secret: false
  when: (secret_value | length) == 0

- set_fact:
    has_secret: true
  when: (secret_value | length) != 0

- debug:
    msg: "Secret {{ secret_name }} lookup resulted in: {{ has_secret }}"