---
environment_name: "{{ global_config.environment_name | default('sample') }}"
cloud_platform: "{{ global_config.cloud_platform | default(omit) }}"
ibm_cloud_region: "{{ global_config.ibm_cloud_region | default(omit) }}"
aws_region: "{{ global_config.aws_region | default(omit) }}"
azure_location: "{{ global_config.azure_location | default(omit) }}"
env_id: "{{ global_config.env_id | default(omit) }}"
universal_admin_user: "{{ global_config.universal_admin_user | default(omit) }}"
universal_password: "{{ global_config.universal_password | default(omit) }}"
_confirm_destroy: "{{ (global_config.confirm_destroy | default(False)) or (confirm_destroy | default(False)) }}"
_cpd_optimize_deploy: "{{ (global_config.optimize_deploy | bool | default(False)) or (cpd_optimize_deploy | bool | default(False)) }}"