- name: Validate True/False Entries
  ansible.builtin.fail:
    msg: "The {{ item.name }} variable has to be boolean"
  when: "item.value  | type_debug != 'bool'"
  with_items:
    - name: openldap_enabled
      value: "{{ openldap_enabled }}"
    - name: pm_enabled
      value: "{{ pm_enabled }}"
    - name: asset_repo_enabled
      value: "{{ asset_repo_enabled }}"
    - name: rpa_enabled
      value: "{{ rpa_enabled }}"
    - name: akhq_enabled
      value: "{{ akhq_enabled }}"
    - name: cerebro_enabled
      value: "{{ cerebro_enabled }}"
    - name: db2mc_enabled
      value: "{{ db2mc_enabled }}"
    - name: pgadmin_enabled
      value: "{{ pgadmin_enabled }}"
    - name: cloudbeaver_enabled
      value: "{{ cloudbeaver_enabled }}"
    - name: roundcube_enabled
      value: "{{ roundcube_enabled }}"
    - name: mongo_express_enabled
      value: "{{ mongo_express_enabled }}"
