---
- name: Validate mandatory variables are defined
  assert:
    that:
      - secret_name is defined
      - secret_name != ''

- name: Get secret from secret file if it was specified
  set_fact:
    secret_value_to_set: "{{ lookup('file', secret_file, rstrip=false) | b64encode }}"
  when: 
  - (secret_file | default('')) != ''

- name: Set secret value from payload if no file specified
  set_fact:
    secret_value_to_set: "{{ secret_payload | b64encode}}"
  when: (secret_file | default('')) == ''

- name: Set Secret Vault Hashicorp
  block:

    - include_tasks: create-secret-hashicorp.yml

  when: vault_type == 'hashicorp-vault'
  rescue:
    #Re-connect to vault
    - include_role:
        name: vault-connect
    
    #Re-attempt the set-secret
    - include_tasks: create-secret.yml

- name: Set secret Vault IBM Cloud
  block:

    - include_tasks: create-secret-ibmcloud.yml
      vars:
        ibmcloud_vault_address: "{{ vault_url }}"
        ibm_cloud_secret_name: "{{ secret_name }}"
        ibm_vault_secret_payload: "{{ secret_value_to_set }}"
  when: "vault_type == 'ibmcloud-vault'"
  rescue:
    #Re-connect to vault
    - include_role:
        name: vault-connect
    
    #Re-attempt the set-secret
    - include_tasks: create-secret.yml  

- name: Set secret in Vault file
  block:
    - include_tasks: create-secret-file.yml
      vars:
        file_secret_payload: "{{ secret_value_to_set }}"
  when: "vault_type == 'file-vault'"

- name: Set secret in Ansible Vault
  block:
    - include_tasks: create-secret-ansible-vault.yml
      vars:
        file_secret_payload: "{{ secret_value_to_set }}"
  when: "vault_type == 'ansible-vault'"
  rescue:
    #Re-connect to vault
    - include_role:
        name: vault-connect
    
    #Re-attempt the set-secret
    - include_tasks: create-secret.yml

- name: Secret {{ secret_group }}/{{ secret_name }} was set
  debug:
    msg: ""
  vars:
    ansible_callback_diy_runner_on_ok_msg: |+2
      Secret {{ secret_group }}/{{ secret_name }} was set
