- name: Set output directory variable
  ansible.builtin.set_fact:
    usage_output_directory: "{{ usage_base_dir }}/{{ usage_dir_name }}"

- name: Remove usage directory for generated files
  ansible.builtin.file:
    path: "{{ usage_output_directory }}"
    state: absent

- name: Install Usage
  ansible.builtin.include_tasks: install.yml
  when: "usage_action == 'install'"

- name: Remove Usage
  ansible.builtin.include_tasks: remove.yml
  when: "usage_action == 'remove'"
