---
- include_role:
    name: log-deployer-activity
  vars:
    _p_activity_description: "{{ _p_command_description }}"
    _p_activity_command: "{{ _p_command }}"

- name: "Run command: {{ _p_command }}, output is in file {{ _p_command_log_file | default('/tmp/command-log-file.log')}}"
  shell: |
    set -o pipefail
    {{ _p_command }} 2>&1 | tee -a {{ _p_command_log_file | default('/tmp/command-log-file.log') }}
  environment: "{{ _p_command_environment | default({}) }}"
  register: _run_command_result
  until: _run_command_result.rc == 0
  retries: "{{ _p_command_retries }}"
  delay: "{{ _p_command_delay | default(15) }}"
  when: not cpd_dry_run