---
- import_playbook: playbook-env-apply-10-validate.yml
- import_playbook: playbook-env-apply-20-prepare.yml
- import_playbook: playbook-env-apply-30-provision-infra.yml
  when: not cpd_skip_infra | bool
- import_playbook: playbook-env-apply-40-configure-infra.yml
  when: not cpd_skip_infra | bool
<<<<<<< HEAD
- import_playbook: playbook-env-apply-50-install-cloud-pak.yml
- import_playbook: playbook-env-apply-80-smoke-tests.yml
=======
- import_playbook: playbook-env-apply-50-install-cloud-pak.yml
>>>>>>> main
