---

# TODO(SJ): (Optional) configure admin password 
# -----------------------------------------------------------------
# Obtain the admin password and store it in the vault for the
# potential later usage. Ref: role 80-smoke-tests/cp4i-cluster-show
#
# Optionally change the admin password.


