---

    # Create OperatorGroup
    # Ref: ''CP4I-install-CLI
    # ---------------------------------------------------------------
    # apiVersion: operators.coreos.com/v1
    # kind: OperatorGroup
    # metadata:
    #   name: ibm-integration-operatorgroup
    #   namespace: cp4i
    # spec:
    #   targetNamespaces:
    #   - cp4i  
