# Example of the functionality call
#
# - name: Remove DB2MC connection
#   ansible.builtin.include_role:
#     name: common
#     tasks_from: remove-db2mc-connection
#   vars:
#     common_db2_db_name: _db_name
#     common_password: "{{ prefix_universal_password }}"
#     common_user: "{{ prefix_admin_user }}"
#     common_output_directory: "{{ prefix_output_directory }}"
#     common_db2_hostname: "{{ prefix_db2_hostname }}"

- name: Get DBMC Pod
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    namespace: db2mc
    label_selectors:
      - app=db2mc
  register: pods
  retries: 40
  delay: 15

- name: Remove db2 connection
  block:

    - name: Get OCP Apps domain
      ansible.builtin.include_role:
        name: common
        tasks_from: apps-endpoint
      vars:
        common_output_to_var: "apps_endpoint_domain"

    - name: Prepare JSON file for db2mc token request
      ansible.builtin.template:
        src: db2mc-token-request.json.j2
        dest: "{{ common_output_directory }}/db2mc-token-request.json"
        mode: u+rwx

    - name: Get auth token
      ansible.builtin.uri:
        url: "https://db2mc.{{ apps_endpoint_domain }}/dbapi/v4/auth/tokens"
        method: POST
        body_format: json
        src: "{{ common_output_directory }}/db2mc-token-request.json"
        status_code: 200
        validate_certs: false
      register: auth_token_response

    - name: Set auth token
      ansible.builtin.set_fact:
        auth_token: "{{ auth_token_response.json | json_query('token') }}"

    - name: Removing DB from DB2MC
      ansible.builtin.uri:
        url: "https://db2mc.{{ apps_endpoint_domain }}/dbapi/v4/dbprofiles/{{ common_db2_db_name }}"
        method: DELETE
        headers:
          Authorization: Bearer {{ auth_token }}
        status_code: [200, 404]
        validate_certs: false

  when: pods.resources | length != 0
