# Based on https://www.enterprisedb.com/blog/how-deploy-pgadmin-kubernetes

- name: Create pgadmin directory for generated files
  ansible.builtin.file:
    path: "{{ pgadmin_output_directory }}"
    state: directory
    mode: u+rwx

- name: Create Project
  ansible.builtin.include_role:
    name: common
    tasks_from: create-project
  vars:
    common_namespace_name: pgadmin
    common_output_directory: "{{ pgadmin_output_directory }}"

- name: Prepare yaml file for PVC
  ansible.builtin.template:
    src: pvc.yaml.j2
    dest: "{{ pgadmin_output_directory }}/pvc.yaml"
    mode: u+rwx

- name: Add PVC
  kubernetes.core.k8s:
    state: present
    force: false
    merge_type: merge
    src: "{{ pgadmin_output_directory }}/pvc.yaml"
    wait: true
    wait_sleep: 15
    wait_timeout: 15

- name: Prepare yaml file for ConfigMap
  ansible.builtin.template:
    src: configmap.yaml.j2
    dest: "{{ pgadmin_output_directory }}/configmap.yaml"
    mode: u+rwx

- name: Add ConfigMap
  kubernetes.core.k8s:
    state: present
    force: false
    merge_type: merge
    src: "{{ pgadmin_output_directory }}/configmap.yaml"
    wait: true
    wait_sleep: 15
    wait_timeout: 15

- name: Prepare yaml file for Secrets
  ansible.builtin.template:
    src: secrets.yaml.j2
    dest: "{{ pgadmin_output_directory }}/secrets.yaml"
    mode: u+rwx

- name: Add Secrets
  kubernetes.core.k8s:
    state: present
    force: false
    merge_type: merge
    src: "{{ pgadmin_output_directory }}/secrets.yaml"
    wait: true
    wait_sleep: 15
    wait_timeout: 15

- name: Prepare yaml file for anyuid RoleBinding
  ansible.builtin.template:
    src: anyuid-scc-rolebinding.yaml.j2
    dest: "{{ pgadmin_output_directory }}/anyuid-scc-rolebinding.yaml"
    mode: u+rwx

- name: Add anyuid RoleBinding
  kubernetes.core.k8s:
    state: present
    force: false
    merge_type: merge
    src: "{{ pgadmin_output_directory }}/anyuid-scc-rolebinding.yaml"
    wait: true
    wait_sleep: 15
    wait_timeout: 15

- name: Prepare yaml file for Deployment
  ansible.builtin.template:
    src: deployment.yaml.j2
    dest: "{{ pgadmin_output_directory }}/deployment.yaml"
    mode: u+rwx

- name: Add Deployment
  kubernetes.core.k8s:
    state: present
    force: false
    merge_type: merge
    src: "{{ pgadmin_output_directory }}/deployment.yaml"
    wait: true
    wait_sleep: 15
    wait_timeout: 600

- name: Prepare yaml file for Service
  ansible.builtin.template:
    src: service.yaml.j2
    dest: "{{ pgadmin_output_directory }}/service.yaml"
    mode: u+rwx

- name: Add Service
  kubernetes.core.k8s:
    state: present
    force: false
    merge_type: merge
    src: "{{ pgadmin_output_directory }}/service.yaml"
    wait: true
    wait_sleep: 15
    wait_timeout: 15

- name: Get OCP Apps Endpoint
  ansible.builtin.include_role:
    name: common
    tasks_from: apps-endpoint
  vars:
    common_output_to_var: "apps_endpoint_domain"
  when: apps_endpoint_domain is not defined

- name: Get OCP Apps Endpoint
  ansible.builtin.include_role:
    name: common
    tasks_from: apps-endpoint
  vars:
    common_output_to_var: "apps_endpoint_domain"
  when: apps_endpoint_domain is not defined

- name: Crete Edge Route
  ansible.builtin.include_role:
    name: common
    tasks_from: create-edge-route
  vars:
    common_namespace_name: pgadmin
    common_route_name: pgadmin
    common_service_name: pgadmin
    common_wildcard_crt_path: "{{ pgadmin_wildcard_crt_path }}"
    common_wildcard_key_path: "{{ pgadmin_wildcard_key_path }}"
    common_ca_crt_path: "{{ pgadmin_ca_crt_path }}"
    common_apps_endpoint_domain: "{{ apps_endpoint_domain }}"
    common_output_directory: "{{ pgadmin_output_directory }}"
