---
- when: "not cp4d_ca_provision_cognos_instance == true"
  block:
    - name: "Skip provision Cognos Analytics instance"
      debug:
        msg: "Variable cp4d_ca_provision_cognos_instance set to {{ cp4d_ca_provision_cognos_instance }}, ending play provision_cognos_instance"

- set_fact:
    ca_cartridge: "{{ current_cp4d_cluster.cartridges|json_query(query_cartridge)|first }}"
  vars:
    cartridge_name: "ca"
    query_cartridge: "[?name=='{{ cartridge_name }}']"

- name: Loop throught each Cognos instance
  block:

  - debug:
    var: ca_cartridge

  - debug:
      msg: "{{ ca_cartridge.instances | length }}"

  - name: Provision each Cognos instance from the Cognos cartridge specification
    include_tasks: provision_cognos_instance.yml
    loop: "{{ ca_cartridge.instances | default([]) }}"
    loop_control:
      loop_var: cognos_instance
    when: ca_cartridge.instances | length > 0

  when: 
    - not ca_cartridge == ""
    - ca_cartridge.instances is defined
    - cp4d_ca_provision_cognos_instance == true

