---
- name: Get secret Validate mandatory variables are defined
  assert:
    that:
      - secret_group is defined
      - secret_name is defined

- name: Fail if a secret field was specified for a vault other than Hashicorp
  fail:
    msg: "Secret name {{ secret_name }} can only have a secret field specification for Hashicorp Vault"
  when: secret_name is search(",")

- name: Check that vault file {{ secret_group }} exists
  stat:
    path: "{{ status_dir }}/vault/{{ secret_group }}"
  register: vault_file_details

- set_fact:
    secret_value: ""

- set_fact:
    _secret_value_b64: "{{ lookup('ini', secret_name + ' type=properties file=' + status_dir + '/vault/' + secret_group) }}"
  when: vault_file_details.stat.exists

- set_fact:
    secret_value: "{{ _secret_value_b64 | b64decode }}"
  when: vault_file_details.stat.exists

- include_tasks: write-secret-to-file.yaml
  when: secret_file | default("") != ''